buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:9.4.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

project(':core') {
    apply plugin: 'java'
    dependencies {
        implementation "com.badlogicgames.gdx:gdx:1.14.2"
    }
}

tasks.register('clean', Delete) {
    delete getLayout().getBuildDirectory()
}
