apply plugin: "com.android.application"

android {
    compileSdk 37

    defaultConfig {
        namespace "at.maui.flopsydroid.android"
        minSdkVersion 25
        targetSdkVersion 37
        versionCode 1
        versionName "1.0"
        signingConfig signingConfigs.debug
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            jniLibs.srcDirs = ['libs']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
        }
    }
}

dependencies {
    implementation project(':core')
    implementation "com.badlogicgames.gdx:gdx:1.14.2"
    implementation "com.badlogicgames.gdx:gdx-backend-android:1.14.2"
    implementation "androidx.appcompat:appcompat:1.8.0"
}
